name: smol ELF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Deps
      run: sudo apt-get install -y nasm
      
    - name: Build
      run: |
        mkdir build
        nasm -f bin -o build/smol src/main.asm
        chmod +x build/smol
        
    - name: Execute
      continue-on-error: true
      run: |
        if ! ./build/smol; then
          echo "::warning::Binary execution failed, but continuing workflow"
        fi
        
    - name: Verify Size
      run: |
        SIZE=$(stat -c%s build/smol)
        echo "Binary size: $SIZE bytes"
        if [ $SIZE -gt 100 ]; then
          echo "::warning::Binary is larger than 100 bytes!"
        fi
        
    - name: Upload Binary
      uses: actions/upload-artifact@v4
      with:
        name: smol-elf
        path: build/smol